@startuml
|UI|
start
:LoginWindow.mostrar();
:LoginWindow.recogerCredenciales();
->

|Authenticator|
:Authenticator.login(user, pass);
if (login OK?) then (sí)
  ->

  |UI|
  :MainWindow.mostrarMenú();
  :MainWindow.seleccionarPizzas();
  :MainWindow.clickCheckout();
  :MainWindow.recogerDatosPago();
  ->

  |PaymentProcessor|
  :PaymentProcessor.procesar(datosPago);
  if (pago OK?) then (sí)
    ->

    |OrderManager|
    :OrderManager.crear(order);
    ->

    |DataBaseManager|
    :insert(order);
    return
    ->

    |UI|
    :Mostrar confirmación;
    stop
  else (no)
    ->

    |UI|
    :Mostrar error de pago;
    stop
  endif
else (no)
  ->

  |UI|
  :Mostrar error de login;
  stop
endif
@enduml
